name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.0
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
      - name: Install dependencies for requirements and testing
        run: |
          python -m pip install --upgrade pip
          if [ -f requirement.txt ]; then pip install -r requirement.txt; fi
          if [ -f requirement_dev.txt ]; then pip install -r requirement_dev.txt; fi
      - name: Test with pytest
        run: |
          pytest --cov src test/ --cov-fail-under=75